
# =========================================================================================== #
# PBS management
qsub:
    qsub_loc: '/glade/u/home/ksha/CONUS-404-prep/qsub/'
    scripts_loc: '/glade/u/home/ksha/CONUS-404-prep/data_preprocessing_GP/scripts/'
    
# =========================================================================================== #
# Z-score and residual norm coef
zscore:
    U: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    V: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    T: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    Q: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    Z: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    MSL: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    SP: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    VAR_2T: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    VAR_10U: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    VAR_10V: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    total_column_water: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    total_precipitation: '/glade/derecho/scratch/ksha/DWC_data/CONUS_domain_GP/dscale_BCSD/ERA5_GP_1h_*.zarr'
    save_loc: '/glade/campaign/ral/hap/ksha/DWC_data/CONUS_domain_GP/temp_dscale_npy/'
    years_range: [1980, 2019]
    prefix: 'zscore_ERA5_1h_1980_2019'





